### ISSUE TITLE
platform_family? regression

### ISSUE THREAD

**Issue by evralston** [sous-chefs/vault#128]
Getting an error using Chef 12.5.1 that was fixed previously in #96 but then undone by #104.

I can't tell if the changes to `libraries/vault_service.rb` in 104 were intentional or accidental, because I don't have enough context about Chef version-specific behaviors... so I didn't want to blindly reopen a PR that does the same thing as 96 if there's a better solution going forward.

```
================================================================================
    Error executing action `enable` on resource 'vault_service[vault]'
    ================================================================================
    
    NoMethodError
    -------------
    No resource or method named `platform_family?' for `VaultCookbook::Provider::VaultService ""'
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/hashicorp-vault/libraries/vault_service.rb:100:in `service_options'
    /var/chef/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:175:in `block in service_resource'
    /var/chef/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:168:in `tap'
    /var/chef/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:168:in `service_resource'
    /var/chef/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:153:in `notify_if_service'
    /var/chef/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_mixin.rb:88:in `action_enable'
    /var/chef/cache/cookbooks/hashicorp-vault/libraries/vault_service.rb:88:in `action_enable'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/hashicorp-vault/recipes/server.rb
    
     28: vault_service node['hashicorp-vault']['service_name'] do |r|
     29:   user node['hashicorp-vault']['service_user']
     30:   group node['hashicorp-vault']['service_group']
     31:   config_path node['hashicorp-vault']['config']['path']
     32:   disable_mlock config.disable_mlock
     33:   program install.vault_program
     34: 
     35:   if node['hashicorp-vault']['service']
     36:     node['hashicorp-vault']['service'].each_pair { |k, v| r.send(k, v) }
     37:   end
     38:   action [:enable, :start]
```

**Comment by tas50** [comment]
@evralston Can you cut a PR to get this back to the old setup?
