### ISSUE TITLE
fix failing tests

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/vault#135]
Circle CI is failing: https://circleci.com/gh/sous-chefs/vault/54

The errors are:
```


An error occurred while loading ./spec/libraries/vault_config_spec.rb.
Failure/Error: require 'poise_boiler/spec_helper'

LoadError:
  cannot load such file -- poise_boiler/spec_helper
# ./spec/libraries/vault_config_spec.rb:3:in `<top (required)>'

An error occurred while loading ./spec/libraries/vault_service_spec.rb.
Failure/Error: require 'poise_boiler/spec_helper'

LoadError:
  cannot load such file -- poise_boiler/spec_helper
# ./spec/libraries/vault_service_spec.rb:3:in `<top (required)>'
```

**Comment by PowerSchill** [comment]
Failing tests are ignored (until we can remove Poise) so I would say that is a fix? :)
